language: minimal
branches:
  only:
  - master

before_deploy:
  - echo -e "Host 142.93.162.43\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_303c572f17fc_key -iv $encrypted_303c572f17fc_iv -in travis/id_rsa.enc -out id_rsa -d

deploy:
  skip_cleanup: true
  provider: script
  script: bash travis/deploy.sh
  on:
    branch: master
