version: '3'
services:
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    network_mode: host
    volumes:
      - /tmp:/tmp
    command:
      "node app.js"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx:/etc/nginx/

  database:
    image: "postgres"
    env_file: 
      - db.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  database-data: 