version: '3'
services:
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - /tmp:/tmp
    command:
      "node app.js"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/