version: '3'
services:
  webapp:
    build: ./app
    container_name: app
    restart: unless-stopped
    network_mode: host
    volumes:
      - /tmp:/tmp
    command:
      "node app.js"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./nginx:/etc/nginx/