version: '3'
services:
  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    ports:
      - "8080"
      - "7070"
    volumes:
      - /tmp:/tmp
    command:
      "node app.js"
  nginx:
    image: nginx:1.17
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/monitor/
    ports:
      - "3000:3000"
volumes:
  grafana-storage:
