{
 "title": "API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"app\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Status 2XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"2XX\", job=\"app\"})"
    }
   ]
  },
  {
   "title": "Status 3XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"3XX\", job=\"app\"})"
    }
   ]
  },
  {
   "title": "Status 4XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"4XX\", job=\"app\"})"
    }
   ]
  },
  {
   "title": "Status 5XX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=\"5XX\", job=\"app\"})"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_request_duration_seconds_sum{job=\"app\"}[1m])) / sum(rate(http_request_duration_seconds_count{job=\"app\"}[1m]))) * 1000"
    }
   ]
  }
 ]
}